run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - goconst
    - gocritic
    - godot
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused

linters-settings:
  gofmt:
    simplify: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-checks:
      - appendCombine
      - argOrder
      - assignOp
      - badCond
      - boolExprSimplify
      - builtinShadow
      - captLocal
      - caseOrder
      - codegenComment
      - commentFormatting
      - commentedOutCode
      - commentedOutImport
      - defaultCaseOrder
      - deprecatedComment
      - docStub
      - dupBranchBody
      - dupCase
      - dupImport
      - emptyFallthrough
      - equalFold
      - elseif
      - emptyStringTest
      - hexLiteral
      - ifElseChain
      - importShadow
      - initClause
      - methodExprCall
      - nestingReduce
      - newDeref
      - nilValReturn
      - octalLiteral
      - paramTypeCombine
      - rangeExprCopy
      - rangeValCopy
      - regexpMust
      - returnAfterHttpError
      - sloppyLen
      - stringXbytes
      - switchTrue
      - typeAssertChain
      - typeSwitchVar
      - typeUnparen
      - underef
      - unlabelStmt
      - unlambda
      - unslice
      - unusedParam
      - uselessString
      - weakCond
      - yodaStyleExpr
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - unused
  exclude:
    - "Error return value of .+ is not checked"
