apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-backend-template.fullname" . }}
  labels:
    {{- include "go-backend-template.labels" . | nindent 4 }}
data:
  # Additional non-secret config can be added here if needed
